# Generated by Django 3.2.10 on 2021-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaapp', '0003_rename_file_name_reciepts_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepts',
            name='creator',
            field=models.BigIntegerField(null=True),
        ),
    ]
